services:
  api:
    build: .
    image: devopstest:local
    container_name: devopstest
    ports:
    - "8000:8000"
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 2s
      retries: 5