# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopstest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopstest
  template:
    metadata:
      labels:
        app: devopstest
    spec:
      containers:
        - name: api
          image: ghcr.io/9imyong/devopstest:latest   # 당신의 태그로 맞추기
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
      # 프라이빗 이미지면 주석 해제
      # imagePullSecrets:
      #   - name: ghcr-creds
